#!/bin/bash
# Install ContextPulse git hooks.
#
# Git doesn't track .git/hooks/, so every fresh clone needs this to enable
# the pre-push publication gate. Run once after cloning.
#
# Usage: bash scripts/install-git-hooks.sh

set -eu

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
SCRIPTS_DIR="$REPO_ROOT/scripts"

# pre-push: run the publication gate (pre-publish.py) before any push.
#
# The hook resolves the repo root when it RUNS, not when it is installed. It used
# to bake in this script's own `git rev-parse --show-toplevel`, which made the
# hook specific to the shell that installed it: installed from Windows Git Bash it
# read `C:/Users/david/projects/ContextPulse/...`, a path that cannot resolve from
# WSL at all, so every push from WSL died with
# "C:/Users/david/projects/ContextPulse/scripts/pre-push-gate.sh: No such file or
# directory" while the script sat right there in the tree. Resolving at run time
# works from both shells and from any clone location. (Fixed 2026-09-15.)
cat > "$HOOKS_DIR/pre-push" <<'HOOK'
#!/bin/bash
# Auto-generated by scripts/install-git-hooks.sh — do not edit directly.
# Source: scripts/pre-push-gate.sh
exec bash "$(git rev-parse --show-toplevel)/scripts/pre-push-gate.sh" "$@"
HOOK
chmod +x "$HOOKS_DIR/pre-push"
chmod +x "$SCRIPTS_DIR/pre-push-gate.sh"

echo "Installed hooks:"
echo "  pre-commit  -> gitleaks (secret scanning, already active)"
echo "  pre-push    -> pre-publish.py gate (BLOCKER = block push)"
echo ""
echo "To bypass in an emergency: git push --no-verify"
echo "(GitHub Actions security.yml still runs — fix any post-push findings fast.)"
