#!/bin/bash
# Install ContextPulse git hooks.
#
# Git doesn't track .git/hooks/, so every fresh clone needs this to enable
# the pre-push publication gate. Run once after cloning.
#
# Usage: bash scripts/install-git-hooks.sh

set -eu

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
SCRIPTS_DIR="$REPO_ROOT/scripts"

# pre-push: run the publication gate (pre-publish.py) before any push.
cat > "$HOOKS_DIR/pre-push" <<HOOK
#!/bin/bash
# Auto-generated by scripts/install-git-hooks.sh — do not edit directly.
# Source: scripts/pre-push-gate.sh
exec bash "$SCRIPTS_DIR/pre-push-gate.sh" "\$@"
HOOK
chmod +x "$HOOKS_DIR/pre-push"
chmod +x "$SCRIPTS_DIR/pre-push-gate.sh"

echo "Installed hooks:"
echo "  pre-commit  -> gitleaks (secret scanning, already active)"
echo "  pre-push    -> pre-publish.py gate (BLOCKER = block push)"
echo ""
echo "To bypass in an emergency: git push --no-verify"
echo "(GitHub Actions security.yml still runs — fix any post-push findings fast.)"
